force-app/main/default/objects/Backlog__c/Backlog__c.object-meta.xml
<CustomObject>
    <label>Backlog</label>
    <nameField>
        <displayFormat>BK-{0000}</displayFormat>
        <label>Backlog Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Backlogs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Backlog__c/fields/KanbanColumn__c.field-meta.xml
<CustomField>
    <fullName>KanbanColumn__c</fullName>
    <label>KanbanColumn</label>
    <referenceTo>KanbanColumn__c</referenceTo>
    <relationshipLabel>Backlogs</relationshipLabel>
    <relationshipName>Backlogs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProjectForce/force-app/main/default/objects/Backlog__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Backlogs</relationshipLabel>
    <relationshipName>Backlogs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Backlog__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KanbanColumn__c/KanbanColumn__c.object-meta.xml
<CustomObject>
    <description>A new kanban column</description>
    <label>KanbanColumn</label>
    <nameField>
        <label>KanbanColumn Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>KanbanColumns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/KanbanColumn__c/fields/Backlog__c.field-meta.xml
<CustomField>
    <fullName>Backlog__c</fullName>
    <label>Backlog</label>
    <referenceTo>Backlog__c</referenceTo>
    <relationshipLabel>KanbanColumns</relationshipLabel>
    <relationshipName>KanbanColumns</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/KanbanColumn__c/fields/Label__c.field-meta.xml
<CustomField>
    <fullName>Label__c</fullName>
    <label>Label</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/KanbanColumn__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/KanbanColumn__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>relate to project</description>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>KanbanColumns</relationshipLabel>
    <relationshipName>KanbanColumns</relationshipName>
    <type>Lookup</type>
</CustomField>

pfbaseobjects/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/KanbanProjectTest.cls
@isTest
public with sharing class KanbanProjectTest {

    @TestSetup
    public static void testSetup() {
        DataFactory.createTestData(200);
    }
    
    @isTest
    public static void testKanbanColumns ()
    {   string project = [ SELECT Id FROM Project__c LIMIT 1 ].id;
        List<KanbanColumn__c> expected = [	SELECT Id, Name, Label__c, Order__c
            								FROM KanbanColumn__c
                							WHERE Project__c =: project
                                         	ORDER BY Order__c ASC
        								 ];
        List<KanbanColumn__c> actual = KanbanProjectApexClass.getKanbanColumns(project);
        System.assertEquals(expected, actual);
    }
    
    @isTest
    public static void testOrderOptions ()
    {	string project = [ SELECT Id FROM Project__c LIMIT 1 ].id;
     	List<string> expected = new List<string> {'1', '2', '3'};
     	List<string> actual = KanbanProjectApexClass.getOrderOptions(project);
        System.assertEquals(expected, actual);
    }
}
    /*
    @isTest
    public static void testSaveBacklog() {
        // Query, change Stage and then Save one Backlog
        Backlog__c backlog = new Backlog__c();
        backlog = [Select Id, Stage__c From Backlog__c Where Stage__c = 'Doing' Limit 1];
        backlog.Stage__c = 'Done';
        KanbanProjectApexClass.saveBacklog(backlog); 
        
        // Query, change Stage, and then Save a List of Backlogs
        List<Backlog__c> backlogs = new List<Backlog__c>();
        backlogs = [Select Id, Stage__c From Backlog__c Where Stage__c = 'Doing'];
        for (backlog__c b : backlogs) {
            b.Stage__c = 'Done';
        }
        KanbanProjectApexClass.saveBacklogs(backlogs);
    }
    
    @isTest
    public static void testgetBacklogs () 
    {   // Query for one project
        Project__c project = new Project__c();
        project = [Select Id, Name, (Select Id, Stage__c From Backlogs__r) From Project__c Limit 1];
        // Mimick the method but only fetch id from each backlog
        List<Backlog__c> expBacklogs = [ SELECT Id FROM Backlog__c WHERE Project__c =: project.Id ];
        List<Backlog__c> backlogs = KanbanProjectApexClass.getBacklogs(project.Id);
        System.assertEquals(expBacklogs.size(), backlogs.size());        
    }
    
    @isTest
    public static void testAddBacklogs ()
    {										// Test no labels
        KanbanProjectApexClass.addNewBacklog(	'Doing', 'Get test coverage to 90%', 
                                             	null, null, null, 
                                             	null, null, null, null
                                            );	// Test one label
        KanbanProjectApexClass.addNewBacklog(	'Doing', 'Get test coverage to 90%', 
                                             	'Label1', null, null, 
                                             	null, null, null, null
                                            );	// Test two labels
        KanbanProjectApexClass.addNewBacklog(	'Doing', 'Get test coverage to 90%', 
                                             	'Label1', 'Label2', null, 
                                             	null, null, null, null
                                            );	// Test one of many fail cases
        KanbanProjectApexClass.addNewBacklog(	'Doing', 'Get test coverage to 90%', 
                                             	'Label1', 'Label2', 'Label3', 
                                             	null, null, null, null
                                            );*/