pfbaseobjects/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

pfbaseobjects/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProjectForce/force-app/main/default/objects/Project__c/fields/ProjectComplete__c.field-meta.xml
<CustomField>
    <fullName>ProjectComplete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Project Complete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Track__c.field-meta.xml
<CustomField>
    <fullName>Track__c</fullName>
    <label>Track</label>
    <referenceTo>Track__c</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Project3/force-app/main/default/objects/Room__c/Room__c.object-meta.xml
<CustomObject>
    <label>Room</label>
    <nameField>
        <label>Room Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rooms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Project3/force-app/main/default/objects/Room__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Rooms</relationshipLabel>
    <relationshipName>Rooms</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Project3/force-app/main/default/objects/Track__c/Track__c.object-meta.xml
<CustomObject>
    <label>Track</label>
    <nameField>
        <label>Technology</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tracks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

pfbaseobjects/main/default/objects/Trainer__c/Trainer__c.object-meta.xml
<CustomObject>
    <label>Trainer</label>
    <nameField>
        <label>Trainer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trainers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Project3/force-app/main/default/objects/Training__c/Training__c.object-meta.xml
<CustomObject>
    <label>Training</label>
    <nameField>
        <label>Training Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trainings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Project3/force-app/main/default/objects/Training__c/fields/Batch_Number__c.field-meta.xml
<CustomField>
    <fullName>Batch_Number__c</fullName>
    <label>Batch Number</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ProjectForce/force-app/main/default/objects/Training__c/fields/BatchSize__c.field-meta.xml
<CustomField>
    <fullName>BatchSize__c</fullName>
    <label>Batch Size</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ProjectForce/force-app/main/default/objects/Training__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <label>Comments</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Training__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <formula>Room__r.Location__r.City__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Location</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Training__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Trainings</relationshipLabel>
    <relationshipName>Trainings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Training__c/fields/ProjectStartDate__c.field-meta.xml
<CustomField>
    <fullName>ProjectStartDate__c</fullName>
    <inlineHelpText>If no Project Start Date is entered when creating a Training object, this field will default to three weeks before the end date of the training.</inlineHelpText>
    <label>ProjectStartDate</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Training__c/fields/Room__c.field-meta.xml
<CustomField>
    <fullName>Room__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Room</label>
    <referenceTo>Room__c</referenceTo>
    <relationshipLabel>Trainings</relationshipLabel>
    <relationshipName>Trainings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Training__c/fields/Track__c.field-meta.xml
<CustomField>
    <fullName>Track__c</fullName>
    <label>Track</label>
    <referenceTo>Track__c</referenceTo>
    <relationshipLabel>Trainings</relationshipLabel>
    <relationshipName>Trainings</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

Project3/force-app/main/default/objects/Training__c/fields/Trainer__c.field-meta.xml
<CustomField>
    <fullName>Trainer__c</fullName>
    <label>Trainer</label>
    <referenceTo>Trainer__c</referenceTo>
    <relationshipLabel>Trainings</relationshipLabel>
    <relationshipName>Trainings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ModalController.cls
//change "without sharing" to "with sharing" when deploying
public without sharing class ModalController {
    //All queries are done when modal is loaded
    static List<Project__c> ProjectList = [SELECT Name, ProjectComplete__c, track__r.name, (SELECT ProjectStartDate__c FROM Trainings__r ORDER BY ProjectStartDate__c desc LIMIT 1) FROM Project__c];
    static List<training__c> trainingList = [SELECT Id, batchsize__c, room__r.location__r.name, track__r.Name, room__r.Name, trainer__r.Name, Project__r.Name FROM training__c];

    @AuraEnabled
    public static Training__c getBatch(String trainingID){
        Training__c selectedBatch = new Training__c();
        try {
            if (schema.SObjectType.location__c.isAccessible()) {
                List<Training__c> batch = [SELECT ID, Batch_Number__c, BatchSize__c, Track__r.Name, ProjectStartDate__c, Project__r.Name, Project__r.Id, Trainer__r.Name, Room__r.Name, Room__r.Location__r.Name FROM Training__c WHERE Id =: Id.valueOf(trainingID) LIMIT 1];

                selectedBatch = batch[0];
                return selectedBatch;
            } else {
                return null;
            }
        } catch(Exception e) {
            throw new AuraHandledException('Batch cannot be found');
        }
    }

    // Gets Projects based on the Batch's training track (e.g. Salesforce) 
	@AuraEnabled
    public static List<Project__c> getProject(String trackName, Date startDateName){
        try{
            if (schema.SObjectType.Project__c.isAccessible()){
                List<Project__c> projectListByTrack = [SELECT ID, Name, ProjectComplete__c, Track__r.Name FROM Project__c WHERE Track__r.Name =: trackName];
                return projectListByTrack;
            }else{
                return null;
            }
        //Catch logic below
        } catch(Exception e){
            throw new AuraHandledException('custom message');
        } finally{
            //Finally logic goes in here
        }
    } 

    //Saves changes to selected batch (training) 
    @auraEnabled
    public static boolean Save(String trainingId, string newProjectName, String newComment){
        id newProjectId = [SELECT Id, ProjectComplete__c FROM Project__c WHERE name = :newProjectName LIMIT 1].id;
        Training__c newTraining=[SELECT id, Project__c, Comments__c FROM Training__c WHERE id = : Id.valueOf(trainingID) LIMIT 1];

        if (newTraining.Comments__c==null){
            newTraining.Comments__c=' ';
        }
        newTraining.Comments__c =  newComment + '\n' + newTraining.Comments__c;
        newTraining.Project__c=newProjectId;

        database.saveResult result = Database.update(newTraining);
        return result.isSuccess();
    }
    
    //New Apex Method in order to update the checkbox status values inside the Project__c and Training__c objects
    @auraEnabled
    public static void updateCheckBoxStatusRecord(Project__c projectStatusToUpdate, Training__c reviewStatusToUpdate){
        UPDATE projectStatusToUpdate;
        UPDATE reviewStatusToUpdate;
    }
}