pfbaseobjects/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Project3/force-app/main/default/objects/Location__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

pfbaseobjects/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Project3/force-app/main/default/objects/Project__c/fields/Details__c.field-meta.xml
<CustomField>
    <fullName>Details__c</fullName>
    <description>Give the details of the project.</description>
    <inlineHelpText>Give the details of the project.</inlineHelpText>
    <label>Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

Project3/force-app/main/default/objects/Project__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Track__c.field-meta.xml
<CustomField>
    <fullName>Track__c</fullName>
    <label>Track</label>
    <referenceTo>Track__c</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Project3/force-app/main/default/objects/Room__c/Room__c.object-meta.xml
<CustomObject>
    <label>Room</label>
    <nameField>
        <label>Room Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rooms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Project3/force-app/main/default/objects/Room__c/fields/Capacity__c.field-meta.xml
<CustomField>
    <fullName>Capacity__c</fullName>
    <label>Capacity</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Project3/force-app/main/default/objects/Room__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Rooms</relationshipLabel>
    <relationshipName>Rooms</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Project3/force-app/main/default/objects/Room__c/fields/Room_Number__c.field-meta.xml
<CustomField>
    <fullName>Room_Number__c</fullName>
    <label>Room Number</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Project3/force-app/main/default/objects/Track__c/Track__c.object-meta.xml
<CustomObject>
    <label>Track</label>
    <nameField>
        <label>Technology</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tracks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

pfbaseobjects/main/default/objects/Trainer__c/Trainer__c.object-meta.xml
<CustomObject>
    <label>Trainer</label>
    <nameField>
        <label>Trainer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trainers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Project3/force-app/main/default/objects/TrainerTrack__c/TrainerTrack__c.object-meta.xml
<CustomObject>
    <label>TrainerTrack</label>
    <nameField>
        <label>Trainer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TrainerTracks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Project3/force-app/main/default/objects/TrainerTrack__c/fields/TrackTrainer__c.field-meta.xml
<CustomField>
    <fullName>TrackTrainer__c</fullName>
    <label>TrackTrainer</label>
    <referenceTo>Track__c</referenceTo>
    <relationshipLabel>TrainerTracks</relationshipLabel>
    <relationshipName>TrainerTracks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Project3/force-app/main/default/objects/TrainerTrack__c/fields/TrainerTrack__c.field-meta.xml
<CustomField>
    <fullName>TrainerTrack__c</fullName>
    <label>TrainerTrack</label>
    <referenceTo>Trainer__c</referenceTo>
    <relationshipLabel>TrainerTracks</relationshipLabel>
    <relationshipName>TrainerTracks</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Project3/force-app/main/default/objects/Training__c/Training__c.object-meta.xml
<CustomObject>
    <label>Training</label>
    <nameField>
        <label>Training Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trainings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Project3/force-app/main/default/objects/Training__c/fields/Batch_Number__c.field-meta.xml
<CustomField>
    <fullName>Batch_Number__c</fullName>
    <label>Batch Number</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Training__c/fields/BatchDuration__c.field-meta.xml
<CustomField>
    <fullName>BatchDuration__c</fullName>
    <label>BatchDuration</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Training__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <formula>Room__r.Location__r.City__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Location</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Training__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Trainings</relationshipLabel>
    <relationshipName>Trainings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Training__c/fields/Room__c.field-meta.xml
<CustomField>
    <fullName>Room__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Room</label>
    <referenceTo>Room__c</referenceTo>
    <relationshipLabel>Trainings</relationshipLabel>
    <relationshipName>Trainings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Training__c/fields/Track__c.field-meta.xml
<CustomField>
    <fullName>Track__c</fullName>
    <label>Track</label>
    <referenceTo>Track__c</referenceTo>
    <relationshipLabel>Trainings</relationshipLabel>
    <relationshipName>Trainings</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

Project3/force-app/main/default/objects/Training__c/fields/Trainer__c.field-meta.xml
<CustomField>
    <fullName>Trainer__c</fullName>
    <label>Trainer</label>
    <referenceTo>Trainer__c</referenceTo>
    <relationshipLabel>Trainings</relationshipLabel>
    <relationshipName>Trainings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ChartCalculationControllerTest.cls
@isTest
public with sharing class ChartCalculationControllerTest {
    public ChartCalculationControllerTest() {

    }

    @TestSetup
    public static void makeData(){
        trainer__c newTrainer1 = new trainer__c(name='Test Trainer 1');
        trainer__c newTrainer2 = new trainer__c(name='Test Trainer 2');
        list<trainer__c> trainerList = new list<trainer__c> {newTrainer1, newTrainer2};
        insert trainerList;

        track__c newTrack = new track__c(name='Salesforce');
        insert newTrack;

        location__c newLocation = new location__c(name='Reston', city__c='Reston');
        insert newLocation;

        list<trainerTrack__c> trainerTrackList = new list<trainerTrack__c>();
        list<track__c> trackIdList = [SELECT id, name FROM track__c];
        list<trainer__c> trainerIdList = [SELECT id, name FROM trainer__c];
        for(integer i = 0; i<2; i++){
            trainerTrack__c t = new trainerTrack__c(name='Test Trainer Track '+i, trackTrainer__c=trackIdList[0].id, trainerTrack__c=trainerIdList[i].id);
            trainerTrackList.add(t);
        }
        Insert trainerTrackList;

        list<Location__c> LocIdList = [SELECT id, name FROM location__c];
        Room__c newRoom1 = new Room__c(name='Test Room 1', location__c=LocIdList[0].id, Room_Number__c= 100, Capacity__c=20);
        Room__c newRoom2 = new Room__c(name='Test Room 2', location__c=LocIdList[0].id, Room_Number__c= 101, Capacity__c=20);
        list<room__c> RoomList = new list<room__c> {newRoom1, newRoom2};
        insert RoomList;

        list<trainerTrack__c> TrainerTrackIdList = [SELECT trackTrainer__r.name FROM trainerTrack__c];
        list<project__c> ProjectList = new list<project__c>();
        project__c newProject = new project__c(name='Test Project', track__c=TrainerTrackIdList[0].trackTrainer__c, Details__c='Test Detail');
        project__c newProject2 = new project__c(name='Test Project2', track__c=TrainerTrackIdList[0].trackTrainer__c, Details__c='Test Detail2');
        ProjectList.add(newProject);
        ProjectList.add(newProject2);
        insert ProjectList;

        list<Room__c> RoomIdList = [SELECT Id, name from Room__c];
        list<project__c> ProjectIDList = [SELECT id FROM Project__c];
        list<training__c> TrainingList = new list<training__c> ();
        Training__c newTraining = new Training__c(name='Test Training 1', Trainer__c=trainerIdList[0].id, Track__c=TrainerTrackIdList[0].trackTrainer__c,
                                            Room__c=RoomIdList[0].id, Project__c=ProjectIDList[0].id, Batch_Number__c=1000, Start_Date__c = System.today()+1, 
                                            BatchDuration__c=10);
        TrainingList.add(newTraining);
        Training__c newTraining2 = new Training__c(name='Test Training 2', Trainer__c=trainerIdList[1].id, Track__c=TrainerTrackIdList[0].trackTrainer__c,
                                            Room__c=RoomIdList[1].id, Project__c=ProjectIDList[0].id, Batch_Number__c=1001, Start_Date__c = System.today()+1, 
                                            BatchDuration__c=10);
        TrainingList.add(newTraining2);
        insert TrainingList;
    }


    @isTest
    public static void TestTrainingsWithProject(){
        integer result = ChartCalculationController.getTrainingsWithProjects();
        System.assertEquals(2, result);
    }

    @isTest
    public static void TestOverLappedProjects(){
        integer result = ChartCalculationController.getOverlappedProject();
        System.assertEquals(1, result);
    }

    @isTest
    public static void TestNumOfProjects(){
        integer result = ChartCalculationController.getNumProjects();
        System.assertEquals(1, result);
    }
}