Project3/force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Project3/force-app/main/default/objects/Room__c/Room__c.object-meta.xml
<CustomObject>
    <label>Room</label>
    <nameField>
        <label>Room Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rooms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Project3/force-app/main/default/objects/Room__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Rooms</relationshipLabel>
    <relationshipName>Rooms</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Project3/force-app/main/default/objects/Track__c/Track__c.object-meta.xml
<CustomObject>
    <label>Track</label>
    <nameField>
        <label>Technology</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tracks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Project3/force-app/main/default/objects/Trainer__c/Trainer__c.object-meta.xml
<CustomObject>
    <label>Trainer</label>
    <nameField>
        <label>Trainer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trainers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Project3/force-app/main/default/objects/Training__c/Training__c.object-meta.xml
<CustomObject>
    <label>Training</label>
    <nameField>
        <label>Training Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trainings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Training__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <formula>Room__r.Location__r.City__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Location</label>
    <type>Text</type>
</CustomField>

Project3/force-app/main/default/objects/Training__c/fields/Room__c.field-meta.xml
<CustomField>
    <fullName>Room__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Room</label>
    <referenceTo>Room__c</referenceTo>
    <relationshipLabel>Trainings</relationshipLabel>
    <relationshipName>Trainings</relationshipName>
    <type>Lookup</type>
</CustomField>

Project3/force-app/main/default/objects/Training__c/fields/Track__c.field-meta.xml
<CustomField>
    <fullName>Track__c</fullName>
    <label>Track</label>
    <referenceTo>Track__c</referenceTo>
    <relationshipLabel>Trainings</relationshipLabel>
    <relationshipName>Trainings</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

Project3/force-app/main/default/objects/Training__c/fields/Trainer__c.field-meta.xml
<CustomField>
    <fullName>Trainer__c</fullName>
    <label>Trainer</label>
    <referenceTo>Trainer__c</referenceTo>
    <relationshipLabel>Trainings</relationshipLabel>
    <relationshipName>Trainings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

Project3/force-app/main/default/classes/ModalController.cls
//change without sharing to with sharing when deploying
public without sharing class ModalController {
	@Auraenabled

    //Return a list of locations available
    public static list<location__c> getLocation(){
        try{
            if (schema.SObjectType.location__c.isAccessible()){
                list<location__c> locList = [SELECT name FROM Location__c];
                return locList;
            }else{
                return null;
            }
        //Catch logic below
        }catch(Exception e){
            throw new AuraHandledException('custom message');
            
        }finally{
            //Finally logic goes in here
        }
    }

    //Get trainers based on the location 
	@AuraEnabled
    public static List<Trainer__c> getTrainer(String locationName){
        try{
            if (schema.SObjectType.Trainer__c.isAccessible()){
            	//list<Trainer__c> TrainerList = [SELECT name FROM Trainer__c];
                List<Trainer__c> TrainerList = [select name, (select name, room__r.location__r.Name from trainings__r) from trainer__c];
                Map<Trainer__c, string> trainerMap= new Map<Trainer__c, string>();

                for(Trainer__c t: TrainerList){
                    for(Training__c tg: t.trainings__r){
                        trainerMap.put(t,tg.room__r.location__r.name);
                    }
                }

                list<trainer__c> filterTrainerList = new list<trainer__c>();
                for(trainer__c t : trainerMap.keyset())
                {
                    if(trainerMap.get(t)==locationName){
                        filterTrainerList.add(t);
                    }
                	//System.debug(t.Name + ' ' + trainerMap.get(t));
                }
                System.debug(filterTrainerList);
                return filterTrainerList;
            }else{
                return null;
            }
        //Catch logic below
        }catch(Exception e){
            throw new AuraHandledException('custom message');
            
        }finally{
            //Finally logic goes in here
        }

        
    } 

    //get rooms based on the location
	@AuraEnabled
    public static List<Room__c> getRoom(String locationName){
        try{
            if (schema.SObjectType.Room__c.isAccessible()){
            	//list<Trainer__c> TrainerList = [SELECT name FROM Trainer__c];
                List<Room__c> RoomList = [select name, location__r.name from room__c];


                list<Room__c> filterRoomList = new list<Room__c>();
                for(room__c r : RoomList)
                {
                    if(r.location__r.name==locationName){
                        filterRoomList.add(r);
                    }
                	//System.debug(t.Name + ' ' + trainerMap.get(t));
                }
                System.debug(filterRoomList);
                return filterRoomList;
            }else{
                return null;
            }
        //Catch logic below
        }catch(Exception e){
            throw new AuraHandledException('custom message');
            
        }finally{
            //Finally logic goes in here
        }

    } 

        //get all tracks
        @Auraenabled
        public static list<Track__c> getTrack(){
            try{
                if (schema.SObjectType.Track__c.isAccessible()){
                    list<Track__c> trackList = [SELECT name FROM Track__c];
                    system.debug(trackList);
                    return trackList;
                }else{
                    return null;
                }
            //Catch logic below
            }catch(Exception e){
                throw new AuraHandledException('custom message');
                
            }finally{
                //Finally logic goes in here
            }
        }


}