pfbaseobjects/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Project3/force-app/main/default/objects/Project__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

Project3/force-app/main/default/objects/Training__c/Training__c.object-meta.xml
<CustomObject>
    <label>Training</label>
    <nameField>
        <label>Training Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trainings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Training__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Trainings</relationshipLabel>
    <relationshipName>Trainings</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Training__c/fields/ProjectStartDate__c.field-meta.xml
<CustomField>
    <fullName>ProjectStartDate__c</fullName>
    <inlineHelpText>If no Project Start Date is entered when creating a Training object, this field will default to three weeks before the end date of the training.</inlineHelpText>
    <label>ProjectStartDate</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

PFChartCalculation/default/classes/ChartCalculationController.cls
public without sharing class ChartCalculationController {
    static List<training__c> trainingList = [SELECT Id, project__c, Start_Date__c FROM training__c];
    static List<project__c> projectList = [SELECT Id, (SELECT projectStartDate__c FROM trainings__r ORDER BY projectStartDate__c ASC) FROM project__c];

    //Get the number of trainings with a project
    @AuraEnabled
    public static Integer getTrainingsWithProjects(){
        Integer trainingsCount=0;
        Date Today = system.today();
        for(training__c t: trainingList){
            if(t.project__c != null && t.Start_Date__c >= Today){
                trainingsCount++;
            }
        }
        return trainingsCount;
    }

    //Get the number of overlapping project
    @AuraEnabled
    public static Integer getOverlappedProject(){
        date today = System.today();
        Integer overlapCount=0;

        //filter out projects that ended before today
        list<project__c> projectsAfterToday=new list<project__c>();
        for (project__c p:projectList){
            if(p.trainings__r.size()==0){
                continue;
            }else if(p.trainings__r[p.trainings__r.size()-1].projectStartDate__c >= (today-21)){
                projectsAfterToday.add(p);
            }
        }

        for(project__c p: projectsAfterToday){
            if(p.trainings__r.size()<=1){
                continue;
            }
            else{
                for(Integer i = 0; i < p.trainings__r.size()-1; i++){
                    Date ProjectDate = p.trainings__r[i].projectStartDate__c;
                    Date nextProjectDate = p.trainings__r[i+1].projectStartDate__c;
                    if((nextProjectDate >= ProjectDate) &&  (nextProjectDate <= (ProjectDate+21))){
                        System.debug(overlapCount);
                        overlapCount++;
                        break;
                    }
                }
            }
        }
        return overlapCount;
    }

    //Get the number of project ended after today
    @AuraEnabled
    public static integer getNumProjects(){
        date today = System.today();
        list<project__c> projectsAfterToday=new list<project__c>();
        for (project__c p:projectList){
            if(p.trainings__r.size()==0){
                continue;
            }else if(p.trainings__r[p.trainings__r.size()-1].projectStartDate__c >= (today-21)){
                projectsAfterToday.add(p);
            }
        }
        return projectsAfterToday.size();
        
    }
}